<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><title>Học sinh</title><link rel="stylesheet" href="assets/style.css"><script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"></script></head>
<body><div id="nav" class="nav"></div><div class="container"><h2>Quản lý học sinh</h2>
<div><input id="ma_hs" placeholder="Mã HS"><input id="ho_dem" placeholder="Họ đệm"><input id="ten" placeholder="Tên"><input id="ngay_sinh" type="date"><input id="ma_lop" placeholder="Mã lớp"><button onclick="save()">Thêm</button></div>
<div><input id="q" placeholder="Tìm kiếm"><button onclick="load()">Tìm</button><button onclick="softDeleteSelected()">Xoá tạm nhiều</button></div>
<table id="tb"></table>
<h3>Import từ Excel (lưu thẳng DB)</h3><input type="file" id="excel" accept=".xlsx,.xls"><button onclick="readExcel()">Đọc file</button><div id="maps"></div><button onclick="applyMap()">Mapping</button><button onclick="saveImport()">Lưu vào CSDL</button><table id="preview"></table>
</div>
<script src="assets/app.js"></script><script>
let imported=[];let mapped=[];
(async()=>{await requireAuth();load();})();
async function load(){const r=await fetch('api/students.php?q='+encodeURIComponent(q.value||''));const d=await r.json();tb.innerHTML='<tr><th></th><th>Mã HS</th><th>Họ đệm</th><th>Tên</th><th>Ngày sinh</th><th>Lớp</th><th>Action</th></tr>'+d.map(x=>`<tr><td><input type='checkbox' value='${x.id}' class='ck'></td><td>${x.ma_hs}</td><td contenteditable onblur="edit(${x.id},'ho_dem',this.innerText)">${x.ho_dem}</td><td contenteditable onblur="edit(${x.id},'ten',this.innerText)">${x.ten}</td><td>${x.ngay_sinh||''}</td><td contenteditable onblur="edit(${x.id},'ma_lop',this.innerText)">${x.ma_lop||''}</td><td><button onclick='del(${x.id})'>Xoá tạm</button></td></tr>`).join('');}
async function save(){await fetch('api/students.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ma_hs:ma_hs.value,ho_dem:ho_dem.value,ten:ten.value,ngay_sinh:ngay_sinh.value,ma_lop:ma_lop.value})});load();}
async function del(id){await fetch('api/students.php',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});load();}
async function softDeleteSelected(){const ids=[...document.querySelectorAll('.ck:checked')].map(x=>+x.value);await fetch('api/students.php',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids})});load();}
async function edit(id,field,val){const row=[...tb.querySelectorAll('tr')].find(tr=>tr.querySelector('.ck')?.value==id);const cells=row.querySelectorAll('td');await fetch('api/students.php',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,ho_dem:cells[2].innerText,ten:cells[3].innerText,ngay_sinh:cells[4].innerText,ma_lop:cells[5].innerText})});}
function readExcel(){const f=excel.files[0];if(!f)return;const rd=new FileReader();rd.onload=e=>{const wb=XLSX.read(e.target.result,{type:'binary'});const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,defval:''});imported=rows;const h=rows[0]||[];maps.innerHTML=['MaHS','HoDem','Ten','NgaySinh','MaLop'].map(k=>`${k}: <select id='m_${k}'>${h.map((v,i)=>`<option value='${i}'>${v}</option>`).join('')}</select>`).join('<br>');};rd.readAsBinaryString(f);}
function applyMap(){const idx=k=>+document.getElementById('m_'+k).value;mapped=imported.slice(1).map(r=>({MaHS:r[idx('MaHS')],HoDem:r[idx('HoDem')],Ten:r[idx('Ten')],NgaySinh:r[idx('NgaySinh')],MaLop:r[idx('MaLop')]}));preview.innerHTML='<tr><th>Mã</th><th>Họ đệm</th><th>Tên</th><th>NS</th><th>Lớp</th></tr>'+mapped.map(r=>`<tr><td>${r.MaHS}</td><td>${r.HoDem}</td><td>${r.Ten}</td><td>${r.NgaySinh}</td><td>${r.MaLop}</td></tr>`).join('');}
async function saveImport(){const r=await fetch('api/students.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'bulk_import',rows:mapped})});const d=await r.json();alert('Đã lưu '+d.count+' dòng');load();}
</script></body></html>
